### ISSUE TITLE
路由器如何实现呢

### ISSUE THREAD

**Issue by carrot117** [makeding/aria2_ban_thunder#1]
有考虑弄进openwrt和padavan里吗

**Comment by makeding** [comment]
路由器的话，需要重写啦，做成shell脚本
因为一般路由器貌似塞不进去node？

**Comment by carrot117** [comment]
> 路由器的话，需要重写啦，做成shell脚本
> 因为一般路由器貌似塞不进去node？

好麻烦的样子

**Comment by carrot117** [comment]
> 路由器的话，需要重写啦，做成shell脚本
> 因为一般路由器貌似塞不进去node？

padavan和openwrt都是Linux内核的吧，应该可以写进去吧

**Comment by makeding** [comment]
> > 路由器的话，需要重写啦，做成shell脚本
> > 因为一般路由器貌似塞不进去node？
> 
> padavan和openwrt都是Linux内核的吧，应该可以写进去吧

可以塞进去 node 的话 就按照 readme.md 安装即可～ 没有什么区别哦
