### ISSUE TITLE
似乎没有启动成功

### ISSUE THREAD

**Issue by HtnrxUNc** [makeding/aria2_ban_thunder#10]
aria2还设置了token
，本脚本是否需要设置？
在/ var /log/ bt ......（脚本后执行禁止掉IP的日志）内没有任何记录，是否说明没有执行本脚本或与后端对接成功？
(规则中也没有任何被捕捉到的ip)
(其他补充，当我尝试命令端执行bash startup.sh的时候会提示缺少npm的模块，解决方法就是直接执行"npm install 缺少的模块")

**Comment by makeding** [comment]
配置文件的 secret 就是填 token 的地方，
如果 token 不正确，那么就会一直报错（几秒输出一次很长的错误日志）
然后安装依赖(yarn / npm install )我没写上去 等下更新下
测试的话 直接执行
`node app.js` 即可
最后 其实可以直接使用 readme.md 提到的 pm2 / systemd 来守护本进程，几个 *.sh 文件最后还是方便路由器用户用的

**Comment by HtnrxUNc** [comment]
> 配置文件的秘密就是令牌的地方，
> 如果令牌不正确，那么就会一直报错（几秒输出一次很长的错误）
> 然后测试安装（yarn / npm install ）我没写上等更新下下
> 的话执行直接
> `node app.js`即可
> 求最后其实可以直接使用readme.md提到的PM2 / systemd来守护本进程，几个* .SH文件最后还是方便路由器用户用的

当我从配置文件中修改正确的token(secret)并且重启守护的进程的时候，我已经看见了连接从我的列表中消失，并且成功的在规则中寻找到了消失掉的ip。
尝试bash是因为需要寻找是否是因为缺少依赖等因素导致脚本运行失败而方便查看输出日志。

**Comment by makeding** [comment]
恭喜～
