### ISSUE TITLE
出现了无法 Ban 掉的情况

### ISSUE THREAD

**Issue by HtnrxUNc** [makeding/aria2_ban_thunder#18]
目前我不知道日志文件的路径，所以无法提供详细完整的日志。
状况描述：
当 aria2b 运行（非aria2 等主进程）一段时间内会 Ban 掉被封锁的客户端，但运行一段时间后，将不再 Ban。
只有当重启 aria2b 之后，才会继续 Ban 掉客户端。

我没有使用systemd 或者 pm2 守护进程，而是使用 screen 将 aria2b 挂载在后台窗口，这是否会导致 aria2b 失效？

我运行 aria2b 时使用
`aria2b -c /root/.aria2/aria2.conf --timeout 864000 -b XL,SD,XF,QN,BD`
该运行指令是否产生了某种错误，导致 aria2b 失效？

该问题情况是否会与硬盘剩余空间不足，其他进程占用内存过高，导致 aria2b 进程卡住，或者突发性 cpu 占用过高导致？
详细排除因素我会持续关注，后续有新的信息我将会更新在此 issues

**Comment by makeding** [comment]
出现这种情况一般还是以 io 性能影响最大，如果 io hang 了话（可以使用 top 命令看头顶 wa ）：

<img width="503" alt="image" src="https://github.com/makeding/aria2b/assets/6511667/16f239a5-475e-4d6c-90cd-5af1dafffe4e">

wa 如果太高，比如说我截图的测试环境 wa 已经高达 86，也就是说 CPU 不工作，都在等读写硬盘。

所以 aria2 也会受影响，表现为 API 一直连不上：


<img width="488" alt="image" src="https://github.com/makeding/aria2b/assets/6511667/92def5f9-5602-4946-a81a-106265d624c1">

作为缓解，可以 git clone 最新版本手动运行测试下（增加了请求超时时间）

**Comment by makeding** [comment]
嗯，正常就好。
新版 1.0.8 版本可以直接更新，已经发布在了 GitHub / npm 。

这个 typo 要不要尝试 fork 项目然后开个 pull request 练手？
