### ISSUE TITLE
运行了一下程序，遇到了两个问题。。

### ISSUE THREAD

**Issue by joyous-coder** [makeding/aria2_ban_thunder#2]
>①config.js中  module.export →module.exports   少了个s，这里会得到一个空的object
>②ipset create 的时候就需要加入timeout 参数，否则后面 ipset add 的时候再添加timeout参数的时候会报错
希望作者可以订正一下

**Comment by joyous-coder** [comment]
还用就是nodejs后台运行用forever运行是更好的选择吧， 
`forever start  -o /var/log/aria2/block.log  /root/.aria2/aria2_ban_thunder/app.js;`
可以顺便打印一下日志

**Comment by makeding** [comment]
hmmm 我自己的话 一般用 pm2
pr已收

**Comment by makeding** [comment]
> systemd的寫法建議：
> 
> 1. after加上aria2本體，不然在aria2之前啟動會導致連線失敗。
> 2. Type改為simple，forking會timeout導致systemctl指令失敗。
> 
> ```ini
> [Unit]
> Description=aria2 ban unwelcome clients via ipset
> After=network.target aria2.service
> 
> [Service]
> Type=simple
> User=root
> Restart=on-failure
> RestartSec=5s
> ExecStart=/usr/bin/node /usr/local/bin/aria2b
> 
> [Install]
> WantedBy=multi-user.target
> ```

Type=simple ok

然后 after 的话，不知道用户会以什么方式守护 aria2 所以应该就不考虑了，有需要可以自己加（也就是增加个注释那样）
