### ISSUE TITLE
有个迅雷漏网之鱼怎么回事？

### ISSUE THREAD

**Issue by linkea131** [makeding/aria2_ban_thunder#7]
https://lza.xw520.fun/Screenshot_20210329_152232.jpg

**Comment by linkea131** [comment]
时不时的有几个没ban掉要么ban掉了还在吸血好像

**Comment by linkea131** [comment]
https://lza.xw520.fun/Screenshot_20210329_205115.jpg

**Comment by makeding** [comment]
执行
`ipset list bt_blacklist`
看看ip有没有躺在里面

`iptables -L`
有没有 bt_blacklist 的过滤规则

都有说明已经屏蔽了。

**Comment by linkea131** [comment]
https://lza.xw520.fun/Screenshot_20210330_110517.jpg
