### ISSUE TITLE
自动启动/重启

### ISSUE THREAD

**Issue by HtnrxUNc** [makeding/aria2_ban_thunder#9]
aria2使用软件来源:ubuntu的apt包
aria2使用版本:1.35.0
aria2使用的配置:aria2完美配置(P3TERX)
前端:ariaNG
脚本守护方法:systemd
遇到问题:近段时间发现本脚本会自动启动aria2,只要处于systemd守护状态下。就算aria2已经启动，依旧会再次启动(启动的aria2进程PID与其他进程相同)，导致aria会不断刷新，任务进度等完成后会丢失。

补充
aria的rpc地址我已经添加证书
前端对接aria2方式为https://域名:6800/jsonrpc
而本脚本的conf中我使用了https://127.0.0.1:6800/jsonrpc
的方式连接

**Comment by makeding** [comment]
https://github.com/makeding/aria2_ban_thunder/blob/9aaf1204e06b314228e7f5e08951ed8829f1f7d8/startup.sh#L16
把这行删了即可

ps: *.sh 脚本不是我写的，配置有点不灵话

**Comment by HtnrxUNc** [comment]
> https://github.com/makeding/aria2_ban_thunder/blob/9aaf1204e06b314228e7f5e08951ed8829f1f7d8/startup.sh#L16
> 
> 
> 把这行长大了
> ps：*.sh脚本不是我写的，配置有点不灵话

删除startup.sh文件中的这一行成功解决问题

**Comment by HtnrxUNc** [comment]
aria2后端设置了token,本脚本是否需要设置?
/var/log/bt……(脚本执行后ban掉ip的日志)内没有任何记录，是否说明没有执行本脚本或对接aria后端成功?

**Comment by HtnrxUNc** [comment]
> aria2 还原设置了令牌,本脚本是否需要设置？
> /var/log/bt……（脚本后执行禁止掉ip的日志）内没有任何记录，是否说明没有执行本脚本或回放再现成功？

我将开启一个新的问题来讨论这件事情
